#!/usr/bin/env python3
"""
Dockerfile Generator for Netcool Docker Builder

Dynamically generates optimized Dockerfiles for IBM Netcool/OMNIbus
components with support for multi-stage builds and best practices.
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional, TextIO
from datetime import datetime


class DockerfileGenerator:
    """
    Generates optimized Dockerfiles for Netcool component installations.

    Supports multi-stage builds, minimized image size, and follows
    Docker best practices for enterprise deployments.
    """

    def __init__(self, config: Dict[str, Any], output_dir: str = '.'):
        """
        Initialize the Dockerfile generator.

        Args:
            config: Validated configuration dictionary
            output_dir: Directory where Dockerfile will be generated
        """
        self.config = config
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.base_image = config['base_image']
        self.build_name = config['build_name']
        self.components = config['components']
        self.metadata = config.get('metadata', {})
        self.build_options = config.get('build_options', {})
        self.multi_stage = self.build_options.get('multi_stage', True)

    def generate(self, dockerfile_path: Optional[str] = None) -> str:
        """
        Generate the Dockerfile.

        Args:
            dockerfile_path: Custom path for the Dockerfile (optional)

        Returns:
            Path to the generated Dockerfile
        """
        if dockerfile_path is None:
            dockerfile_path = self.output_dir / 'Dockerfile'
        else:
            dockerfile_path = Path(dockerfile_path)

        with open(dockerfile_path, 'w', encoding='utf-8') as f:
            if self.multi_stage:
                self._generate_multistage_dockerfile(f)
            else:
                self._generate_single_stage_dockerfile(f)

        return str(dockerfile_path)

    def _write_header(self, f: TextIO) -> None:
        """Write Dockerfile header with metadata."""
        f.write(f"# Dockerfile for {self.build_name}\n")
        f.write(f"# Generated on: {datetime.now().isoformat()}\n")
        f.write("# IBM Netcool/OMNIbus Docker Image\n")
        f.write("#\n")
        f.write("# This Dockerfile is auto-generated by netcool_builder\n")
        f.write("# DO NOT EDIT MANUALLY\n")
        f.write("\n")

    def _generate_multistage_dockerfile(self, f: TextIO) -> None:
        """
        Generate a multi-stage Dockerfile.

        Multi-stage builds separate installation from runtime,
        reducing final image size.
        """
        self._write_header(f)

        # Stage 1: Builder stage
        f.write("# ============================================\n")
        f.write("# Stage 1: Builder - Install components\n")
        f.write("# ============================================\n")
        f.write(f"FROM {self.base_image} AS builder\n\n")

        self._write_build_args(f)
        self._write_builder_stage_setup(f)
        self._write_component_installations(f, stage='builder')

        # Stage 2: Runtime stage
        f.write("\n# ============================================\n")
        f.write("# Stage 2: Runtime - Minimal final image\n")
        f.write("# ============================================\n")
        f.write(f"FROM {self.base_image} AS runtime\n\n")

        self._write_runtime_stage_setup(f)
        self._write_copy_from_builder(f)
        self._write_metadata_labels(f)
        self._write_runtime_configuration(f)
        self._write_entrypoint(f)

    def _generate_single_stage_dockerfile(self, f: TextIO) -> None:
        """Generate a single-stage Dockerfile."""
        self._write_header(f)

        f.write(f"FROM {self.base_image}\n\n")

        self._write_build_args(f)
        self._write_builder_stage_setup(f)
        self._write_component_installations(f, stage='single')
        self._write_metadata_labels(f)
        self._write_runtime_configuration(f)
        self._write_entrypoint(f)

    def _write_build_args(self, f: TextIO) -> None:
        """Write ARG declarations for build arguments."""
        build_args = self.build_options.get('build_args', {})
        if not build_args:
            return

        f.write("# Build Arguments\n")
        for key, value in build_args.items():
            f.write(f"ARG {key}={value}\n")
        f.write("\n")

    def _write_builder_stage_setup(self, f: TextIO) -> None:
        """Write setup commands for the builder stage."""
        f.write("# Update system and install dependencies\n")
        f.write("RUN set -eux; \\\n")
        f.write("    yum update -y && \\\n")
        f.write("    yum install -y \\\n")
        f.write("        wget \\\n")
        f.write("        unzip \\\n")
        f.write("        tar \\\n")
        f.write("        gzip \\\n")
        f.write("        which \\\n")
        f.write("        procps \\\n")
        f.write("        net-tools && \\\n")
        f.write("    yum clean all && \\\n")
        f.write("    rm -rf /var/cache/yum\n\n")

        # Create installation directories
        f.write("# Create installation directories\n")
        install_dirs = set()
        for component in self.components:
            if 'install_dir' in component:
                install_dirs.add(os.path.dirname(component['install_dir']))

        if install_dirs:
            dirs_str = ' '.join(sorted(install_dirs))
            f.write(f"RUN mkdir -p {dirs_str}\n\n")

    def _write_component_installations(self, f: TextIO, stage: str) -> None:
        """
        Write component installation commands.

        Args:
            f: File object to write to
            stage: Build stage ('builder', 'single')
        """
        f.write("# Install Netcool components\n")

        # Copy repositories if specified
        source_repos = self.config.get('source_repos', [])
        if source_repos:
            f.write("# Copy installation repositories\n")
            for idx, repo in enumerate(source_repos):
                if 'path' in repo:
                    repo_path = repo['path']
                    dest_path = f"/tmp/repo_{idx}"
                    f.write(f"COPY {repo_path} {dest_path}\n")
            f.write("\n")

        # Install IBM Installation Manager if needed
        imcl_components = [c for c in self.components if c.get('package_id')]
        if imcl_components:
            self._write_imcl_installation(f)

        # Install each component
        for component in self.components:
            self._write_component_installation(f, component)

    def _write_imcl_installation(self, f: TextIO) -> None:
        """Write IBM Installation Manager installation commands."""
        f.write("# Install IBM Installation Manager\n")
        f.write("RUN set -eux; \\\n")
        f.write("    IM_INSTALL_DIR=/opt/IBM/InstallationManager; \\\n")
        f.write("    mkdir -p ${IM_INSTALL_DIR}; \\\n")
        f.write("    # Download and extract IBM IM (placeholder - use actual repo)\n")
        f.write("    echo 'NOTE: IBM IM installation should be provided via repository'\n\n")

    def _write_component_installation(self, f: TextIO, component: Dict[str, Any]) -> None:
        """
        Write installation commands for a single component.

        Args:
            f: File object to write to
            component: Component configuration dictionary
        """
        comp_name = component['name']
        comp_type = component['type']

        f.write(f"# Install {comp_type}: {comp_name}\n")

        if 'package_id' in component:
            # Install using IBM Installation Manager
            package_id = component['package_id']
            install_dir = component.get('install_dir', f'/opt/IBM/{comp_name}')

            f.write("RUN set -eux; \\\n")
            f.write(f"    IMCL_PATH=/opt/IBM/InstallationManager/eclipse/tools/imcl; \\\n")
            f.write(f"    ${{IMCL_PATH}} install {package_id} \\\n")
            f.write(f"        -repositories /tmp/repo_* \\\n")
            f.write(f"        -installationDirectory {install_dir} \\\n")
            f.write(f"        -acceptLicense \\\n")
            f.write(f"        -showProgress\n\n")
        else:
            # Custom installation (placeholder)
            f.write(f"# Custom installation for {comp_name}\n")
            f.write(f"RUN echo 'Custom installation logic for {comp_name}'\n\n")

        # Set environment variables if specified
        if 'env_vars' in component:
            f.write(f"# Environment variables for {comp_name}\n")
            for key, value in component['env_vars'].items():
                f.write(f"ENV {key}={value}\n")
            f.write("\n")

    def _write_runtime_stage_setup(self, f: TextIO) -> None:
        """Write setup commands for the runtime stage."""
        f.write("# Install runtime dependencies only\n")
        f.write("RUN set -eux; \\\n")
        f.write("    yum update -y && \\\n")
        f.write("    yum install -y \\\n")
        f.write("        procps \\\n")
        f.write("        net-tools \\\n")
        f.write("        which && \\\n")
        f.write("    yum clean all && \\\n")
        f.write("    rm -rf /var/cache/yum\n\n")

        # Create runtime user
        f.write("# Create runtime user for security\n")
        f.write("RUN groupadd -r netcool && \\\n")
        f.write("    useradd -r -g netcool -m -d /home/netcool netcool\n\n")

    def _write_copy_from_builder(self, f: TextIO) -> None:
        """Copy installed components from builder stage."""
        f.write("# Copy installed components from builder\n")

        install_paths = set()
        for component in self.components:
            if 'install_dir' in component:
                install_paths.add(component['install_dir'])

        for path in sorted(install_paths):
            f.write(f"COPY --from=builder {path} {path}\n")

        f.write("\n")

        # Fix ownership
        f.write("# Set proper ownership\n")
        for path in sorted(install_paths):
            f.write(f"RUN chown -R netcool:netcool {path}\n")
        f.write("\n")

    def _write_metadata_labels(self, f: TextIO) -> None:
        """Write Docker LABEL instructions for metadata."""
        labels = self.metadata.get('labels', {})

        # Add default labels
        default_labels = {
            'com.ibm.netcool.build_name': self.build_name,
            'com.ibm.netcool.build_date': datetime.now().isoformat(),
            'com.ibm.netcool.version': self.metadata.get('version', '1.0.0'),
        }

        # Add maintainer if specified
        if 'maintainer' in self.metadata:
            default_labels['maintainer'] = self.metadata['maintainer']

        # Merge with user-specified labels
        all_labels = {**default_labels, **labels}

        if all_labels:
            f.write("# Metadata labels\n")
            for key, value in sorted(all_labels.items()):
                # Escape quotes in values
                safe_value = str(value).replace('"', '\\"')
                f.write(f'LABEL {key}="{safe_value}"\n')
            f.write("\n")

    def _write_runtime_configuration(self, f: TextIO) -> None:
        """Write runtime configuration."""
        # Switch to runtime user
        f.write("# Switch to non-root user\n")
        f.write("USER netcool\n")
        f.write("WORKDIR /home/netcool\n\n")

        # Expose ports if specified
        ports = self.build_options.get('expose_ports', [])
        if ports:
            f.write("# Expose ports\n")
            for port in ports:
                f.write(f"EXPOSE {port}\n")
            f.write("\n")

    def _write_entrypoint(self, f: TextIO) -> None:
        """Write ENTRYPOINT and CMD instructions."""
        entrypoint = self.build_options.get('entrypoint')
        cmd = self.build_options.get('cmd')

        if entrypoint:
            f.write("# Entrypoint\n")
            if isinstance(entrypoint, list):
                entry_str = '["' + '", "'.join(entrypoint) + '"]'
            else:
                entry_str = f'["{entrypoint}"]'
            f.write(f"ENTRYPOINT {entry_str}\n\n")

        if cmd:
            f.write("# Default command\n")
            if isinstance(cmd, list):
                cmd_str = '["' + '", "'.join(cmd) + '"]'
            else:
                cmd_str = f'["{cmd}"]'
            f.write(f"CMD {cmd_str}\n\n")

    def generate_dockerignore(self, path: Optional[str] = None) -> str:
        """
        Generate a .dockerignore file.

        Args:
            path: Custom path for .dockerignore (optional)

        Returns:
            Path to the generated .dockerignore file
        """
        if path is None:
            path = self.output_dir / '.dockerignore'
        else:
            path = Path(path)

        ignore_patterns = [
            "# Generated .dockerignore",
            "# Ignore version control",
            ".git/",
            ".gitignore",
            "",
            "# Ignore Python cache",
            "__pycache__/",
            "*.pyc",
            "*.pyo",
            "*.pyd",
            ".Python",
            "",
            "# Ignore build artifacts",
            "*.log",
            "*.tmp",
            "*.swp",
            "",
            "# Ignore documentation",
            "*.md",
            "docs/",
            "",
            "# Ignore test files",
            "tests/",
            "test_*/",
            "",
            "# Ignore IDE files",
            ".vscode/",
            ".idea/",
            "*.swp",
            "",
            "# Credentials (should never be in context anyway)",
            "*.key",
            "*.pem",
            "*.crt",
            "credentials.json",
            ".env",
        ]

        with open(path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(ignore_patterns))
            f.write('\n')

        return str(path)


if __name__ == '__main__':
    # Simple test
    import json
    import sys

    if len(sys.argv) != 2:
        print("Usage: python dockerfile_generator.py <config.json>")
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        config = json.load(f)

    generator = DockerfileGenerator(config)
    dockerfile_path = generator.generate()
    dockerignore_path = generator.generate_dockerignore()

    print(f"✓ Generated Dockerfile: {dockerfile_path}")
    print(f"✓ Generated .dockerignore: {dockerignore_path}")
